config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'
  resources :events
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :email_send

  belongs_to :user
  belongs_to :event

  def email_send
    event = self.event
    event_admin = event.event_admin
    UserMailer.event_subscription(event_admin, event, user).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true, if: :in_the_futur
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }, if: :is_multiple_five?
  validates :title, presence: true, length: {in: 5..140}
  validates :description, presence: true, length: {in: 20..1000}
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :event_admin, class_name: "User"

  def in_the_futur
    errors.add(:start_date, "You can't create an even in the past.") unless start_date > DateTime.now
  end

  def is_multiple_five?
    errors.add(:duration, "Must be a multiple of five!") unless duration % 5 == 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send
  
  has_many :attendances
  has_many :events, through: :attendances
  has_many :admin_events, foreign_key: "event_admin_id", class_name: "Event", dependent: :destroy

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.event_admin = current_user

    if @event.save 
      flash[:notice] = "Event created with success!"
      redirect_to root_path
    else
      flash[:alert] = "Failed to create a new evant - missing/wrong informations "
      render :new
    end
  end

  def event_params
    params.require(:event).permit(:title, :start_date, :duration, :location, :description, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit]

  def show
    @user = User.find(params[:id])
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(post_params)
      flash[:notice] = "Your profil has been updated with success!"
      redirect_to user_path
    else
      flash[:alert] = "Your profil falied to update, missing or wrong informations!"
      render :new
    end
  end

  def post_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="jumbotron jumbotron-fluid text-center" style="background-image: url(https://i.pinimg.com/564x/fc/c1/76/fcc1766d1ba599fc8e5b1ac28e38ab6b.jpg)">
  <div class="container">
    <div class="box mx-auto">
      <h1 class="display-1"><strong>Eventbrite</strong></h1>
      <p class="lead">
        <%= link_to "Create a new event!", new_event_path, :class => "btn btn-outline-dark btn-lg"%>
      </p><br>
    </div>
  </div>
</div>



<div class="container">
  <div class="text-center">
  <h2> All events around!</h2><br>
  </div><br>
  <div class="row mb-3 col">
    <% @events.each do |event| %>
      <div class="card mx-auto" style="width: 18rem;">
        <div class="card-header text-center">
          <h5 class="card-title"> <b><%= event.title%></b></h5>
        </div>
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Start:</b><%=event.start_date%></li>
            <li class="list-group-item"><b>Location:</b> <%=event.location%></li>
            <li class="list-group-item"><b>Price:</b> <%=event.price %> $</li>
            <li class="list-group-item text-center"><%=link_to "More about this event", event_path(event.id), :class => "btn btn-secondary"%></li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<html>
  <body>
  <div class="container "><br>
    <h2>Create a new event</h2><br>
    <%=form_for @event do |f|%>

      <form>
        <div class="form-group">
          <b><%= f.label :title%></b>
          <%= f.text_field :title, class: "form-control", placeholder:"enter a title for your event"%>
          <small class="form-text text-muted">between 5 to 140 caracters</small>
        </div>
        <div class="form-group">
          <b><%= f.label :description%></b>
          <%= f.text_area :description, rows:"3", class: "form-control", placeholder:"enter a description"%>
        </div>

        <div class="form-row">
          <div class="form-group col-md-6">
            <b><%= f.label :location%></b>
            <%= f.text_field :location, class: "form-control", placeholder:"insert the location of your event"%>
          </div>
          <div class="form-group col-md-6">
            <b><%= f.label :start_date%></b>
            <%= f.datetime_field :start_date, autocomplete: "YYYY-MM-DD HH:MM:SS", class: "form-control", placeholder:"YYYY-MM-DD HH:MM:SS"%>
            <small class="form-text text-muted">cannot be in the past</small>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-6">
            <b><%= f.label :price%></b>
            <%= f.text_field :price, class: "form-control", placeholder:"price in dollar"%>
          </div>
          <div class="form-group col-md-6">
            <b><%= f.label :duration%></b>
            <%= f.datetime_field :duration, class: "form-control", placeholder:"in minutes"%>
            <small class="form-text text-muted">must be a multiple of 5</small>
          </div>
        </div><br>
        <div class="form-group text-center">
          <button type="submit" class="btn btn-outline-primary">Create the event</button>
        </div>
      </form>

    <% end %>
    </div>
  </body>
</html>

app/views/events/show.html.erb
<html>
  <body>
    <div class="container mx-auto col-md-9">
      <div class="text-center"><br>
      <h2><%=@event.title%></h2><br>
      </div>
      <div class="card mx-auto col-md-10" >
        <div class="card-body">
          <ul class="list-group list-group-flush">
          <li class="list-group-item"><u><b>Description:</u></b><br><br><%= @event.description%></li>
          <li class="list-group-item"><u><b>Start:</u></b><br><br><%= @event.start_date%></li>
          <li class="list-group-item"><u><b>Duration:</u></b><br><br><%= @event.duration%> minutes</li>
          <li class="list-group-item"><u><b>Location:</u></b><br><br><%= @event.location%></li>
          <li class="list-group-item"><u><b>Price:</u></b><br><br><%= @event.price%> $</li>
        </div>
      </div>
      <div class="text-center">
      <%=link_to "Attend this event", root_path, :class => "btn btn-success"%>
      </div><br><br>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBriteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-white shadow">
      <%= link_to "Event Brite", root_path, :class => "navbar-brand ml-5" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-3">
          <%= link_to "Home", root_path, :class => "nav-link"%>
          <%= link_to "Create an event", new_event_path, :class => "nav-link"%>
          </div>

        <ul class="navbar-nav ml-auto mr-5">
          <% if user_signed_in? %>
            <%= link_to "my profil", user_path(current_user.id), class:"btn btn-primary mr-3"%>
            <%= link_to "Log out", destroy_user_session_path, class: "btn btn-danger", method:"delete", :data => {:confirm => "Do you really want to Log out?"}%>
          <% else %>
            <div class="btn-group">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Connexion
              </button>

              <div class="dropdown-menu dropdown-menu-right">
              <%= link_to "Sign in", new_user_session_path, :class => "dropdown-item"%>
              <%= link_to "Create a new account", new_user_registration_path, :class => "dropdown-item"%>
              </div>
            </div>
        <% end %>
      </div>
    </nav>
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %> 
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container mx-auto col-md-6"><br>
<h2>Update your informations:</h2><br>
  <%= form_for @user do |f|%>

    <label><b><u> First name </b></u></label>
    <%= f.text_field :first_name, class: "form-control" %>
    <br><br>

    <label><b><u> Last name </u></b></label>
    <%= f.text_field :last_name, class: "form-control" %>
    <br><br>

    <label><b><u> Description </u></b></label>
    <%= f.text_area :description, rows:"3", class: "form-control" %>
    <br><br>
    <div class="text-center"><br><br>
    <%= submit_tag "Update your profil", class: 'btn btn-primary' %>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mx-auto">
  <br><br>
  <div class="card mx-auto col-md-10">
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item "><b>Last name :</b> <%=@user.first_name%></li>
        <li class="list-group-item "><b>First name :</b> <%=@user.last_name%></li>
        <li class="list-group-item "><b>Email :</b> <%=@user.email%></li>
        <li class="list-group-item "><b>Description :</b> <%=@user.description%></li>
      </ul>
    </div>
  </div>
  <br>
  <div>
    <%= link_to "Edit profile", edit_user_path, class:"btn btn-secondary " %>
  </div><br>
  <div>
    <%= link_to "Edit email / password", edit_user_registration_path, class:"btn btn-secondary " %>
  </div>

</div>